export const ALLOW = 'allow'
export const FUNCTION = 'function'
export const LET = 'let'
export const IF = 'if'
export const IS = 'is'
export const MATCH = 'match'
export const RETURN = 'return'
export const SERVICE = 'service'
